<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/accountMaintenance/reservations"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="createFundReservation">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/accountMaintenance/reservations" schemaLocation="../FlowDescription/createFundReservation.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="createFundReservationRequestFlow">
		<wsdl:part name="createFundReservationRequestFlow" element="pre1:createFundReservationRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="createFundReservationResponseFlow">
		<wsdl:part name="createFundReservationResponseFlow" element="pre1:createFundReservationResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="createFundReservation">
		<wsdl:operation name="createFundReservation">
			<wsdl:input message="preAmp:createFundReservationRequestFlow" name="createFundReservationRequestFlow"/>
			<wsdl:output message="preAmp:createFundReservationResponseFlow" name="createFundReservationResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="createFundReservation-binding" type="preAmp:createFundReservation">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="createFundReservation">
			<soap:operation soapAction="createFundReservation"/>
			<wsdl:input name="createFundReservationRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="createFundReservationResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="createFundReservation">
		<wsdl:port binding="preAmp:createFundReservation-binding" name="createFundReservation">
			<soap:address location="http://localhost:8080/createFundReservation"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>