<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/meansOfPayment/cheques"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="createChequeBookRequest">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/meansOfPayment/cheques" schemaLocation="../FlowDescription/createChequeBookRequest.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="createChequeBookRequestRequestFlow">
		<wsdl:part name="createChequeBookRequestRequestFlow" element="pre1:createChequeBookRequestRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="createChequeBookRequestResponseFlow">
		<wsdl:part name="createChequeBookRequestResponseFlow" element="pre1:createChequeBookRequestResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="createChequeBookRequest">
		<wsdl:operation name="createChequeBookRequest">
			<wsdl:input message="preAmp:createChequeBookRequestRequestFlow" name="createChequeBookRequestRequestFlow"/>
			<wsdl:output message="preAmp:createChequeBookRequestResponseFlow" name="createChequeBookRequestResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="createChequeBookRequest-binding" type="preAmp:createChequeBookRequest">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="createChequeBookRequest">
			<soap:operation soapAction="createChequeBookRequest"/>
			<wsdl:input name="createChequeBookRequestRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="createChequeBookRequestResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="createChequeBookRequest">
		<wsdl:port binding="preAmp:createChequeBookRequest-binding" name="createChequeBookRequest">
			<soap:address location="http://localhost:8080/createChequeBookRequest"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>