<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/accountMaintenance/accounts"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="getAccountList">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/accountMaintenance/accounts" schemaLocation="../FlowDescription/getAccountList.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getAccountListRequestFlow">
		<wsdl:part name="getAccountListRequestFlow" element="pre1:getAccountListRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="getAccountListResponseFlow">
		<wsdl:part name="getAccountListResponseFlow" element="pre1:getAccountListResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="getAccountList">
		<wsdl:operation name="getAccountList">
			<wsdl:input message="preAmp:getAccountListRequestFlow" name="getAccountListRequestFlow"/>
			<wsdl:output message="preAmp:getAccountListResponseFlow" name="getAccountListResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="getAccountList-binding" type="preAmp:getAccountList">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getAccountList">
			<soap:operation soapAction="getAccountList"/>
			<wsdl:input name="getAccountListRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getAccountListResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="getAccountList">
		<wsdl:port binding="preAmp:getAccountList-binding" name="getAccountList">
			<soap:address location="http://localhost:8080/getAccountList"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>