<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/accountMaintenance/accounts"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="getAccountDetail">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/accountMaintenance/accounts" schemaLocation="../FlowDescription/getAccountDetail.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getAccountDetailRequestFlow">
		<wsdl:part name="getAccountDetailRequestFlow" element="pre1:getAccountDetailRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="getAccountDetailResponseFlow">
		<wsdl:part name="getAccountDetailResponseFlow" element="pre1:getAccountDetailResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="getAccountDetail">
		<wsdl:operation name="getAccountDetail">
			<wsdl:input message="preAmp:getAccountDetailRequestFlow" name="getAccountDetailRequestFlow"/>
			<wsdl:output message="preAmp:getAccountDetailResponseFlow" name="getAccountDetailResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="getAccountDetail-binding" type="preAmp:getAccountDetail">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getAccountDetail">
			<soap:operation soapAction="getAccountDetail"/>
			<wsdl:input name="getAccountDetailRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getAccountDetailResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="getAccountDetail">
		<wsdl:port binding="preAmp:getAccountDetail-binding" name="getAccountDetail">
			<soap:address location="http://localhost:8080/getAccountDetail"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>