<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/codingSystems/banks"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="getBankDetail">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/codingSystems/banks" schemaLocation="../FlowDescription/getBankDetail.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getBankDetailRequestFlow">
		<wsdl:part name="getBankDetailRequestFlow" element="pre1:getBankDetailRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="getBankDetailResponseFlow">
		<wsdl:part name="getBankDetailResponseFlow" element="pre1:getBankDetailResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="getBankDetail">
		<wsdl:operation name="getBankDetail">
			<wsdl:input message="preAmp:getBankDetailRequestFlow" name="getBankDetailRequestFlow"/>
			<wsdl:output message="preAmp:getBankDetailResponseFlow" name="getBankDetailResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="getBankDetail-binding" type="preAmp:getBankDetail">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getBankDetail">
			<soap:operation soapAction="getBankDetail"/>
			<wsdl:input name="getBankDetailRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getBankDetailResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="getBankDetail">
		<wsdl:port binding="preAmp:getBankDetail-binding" name="getBankDetail">
			<soap:address location="http://localhost:8080/getBankDetail"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>