<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/codingSystems/banks"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="getBankAddressDetail">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/codingSystems/banks" schemaLocation="../FlowDescription/getBankAddressDetail.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getBankAddressDetailRequestFlow">
		<wsdl:part name="getBankAddressDetailRequestFlow" element="pre1:getBankAddressDetailRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="getBankAddressDetailResponseFlow">
		<wsdl:part name="getBankAddressDetailResponseFlow" element="pre1:getBankAddressDetailResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="getBankAddressDetail">
		<wsdl:operation name="getBankAddressDetail">
			<wsdl:input message="preAmp:getBankAddressDetailRequestFlow" name="getBankAddressDetailRequestFlow"/>
			<wsdl:output message="preAmp:getBankAddressDetailResponseFlow" name="getBankAddressDetailResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="getBankAddressDetail-binding" type="preAmp:getBankAddressDetail">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getBankAddressDetail">
			<soap:operation soapAction="getBankAddressDetail"/>
			<wsdl:input name="getBankAddressDetailRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getBankAddressDetailResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="getBankAddressDetail">
		<wsdl:port binding="preAmp:getBankAddressDetail-binding" name="getBankAddressDetail">
			<soap:address location="http://localhost:8080/getBankAddressDetail"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>