<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/codingSystems/customers"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="getCustomerRelationList">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/codingSystems/customers" schemaLocation="../FlowDescription/getCustomerRelationList.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getCustomerRelationListRequestFlow">
		<wsdl:part name="getCustomerRelationListRequestFlow" element="pre1:getCustomerRelationListRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="getCustomerRelationListResponseFlow">
		<wsdl:part name="getCustomerRelationListResponseFlow" element="pre1:getCustomerRelationListResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="getCustomerRelationList">
		<wsdl:operation name="getCustomerRelationList">
			<wsdl:input message="preAmp:getCustomerRelationListRequestFlow" name="getCustomerRelationListRequestFlow"/>
			<wsdl:output message="preAmp:getCustomerRelationListResponseFlow" name="getCustomerRelationListResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="getCustomerRelationList-binding" type="preAmp:getCustomerRelationList">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getCustomerRelationList">
			<soap:operation soapAction="getCustomerRelationList"/>
			<wsdl:input name="getCustomerRelationListRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getCustomerRelationListResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="getCustomerRelationList">
		<wsdl:port binding="preAmp:getCustomerRelationList-binding" name="getCustomerRelationList">
			<soap:address location="http://localhost:8080/getCustomerRelationList"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>