<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/savings/termDeposit"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="getTDIncreasInterestRatesList">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/savings/termDeposit" schemaLocation="../FlowDescription/getTDIncreasInterestRatesList.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getTDIncreasInterestRatesListRequestFlow">
		<wsdl:part name="getTDIncreasInterestRatesListRequestFlow" element="pre1:getTDIncreasInterestRatesListRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="getTDIncreasInterestRatesListResponseFlow">
		<wsdl:part name="getTDIncreasInterestRatesListResponseFlow" element="pre1:getTDIncreasInterestRatesListResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="getTDIncreasInterestRatesList">
		<wsdl:operation name="getTDIncreasInterestRatesList">
			<wsdl:input message="preAmp:getTDIncreasInterestRatesListRequestFlow" name="getTDIncreasInterestRatesListRequestFlow"/>
			<wsdl:output message="preAmp:getTDIncreasInterestRatesListResponseFlow" name="getTDIncreasInterestRatesListResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="getTDIncreasInterestRatesList-binding" type="preAmp:getTDIncreasInterestRatesList">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getTDIncreasInterestRatesList">
			<soap:operation soapAction="getTDIncreasInterestRatesList"/>
			<wsdl:input name="getTDIncreasInterestRatesListRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getTDIncreasInterestRatesListResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="getTDIncreasInterestRatesList">
		<wsdl:port binding="preAmp:getTDIncreasInterestRatesList-binding" name="getTDIncreasInterestRatesList">
			<soap:address location="http://localhost:8080/getTDIncreasInterestRatesList"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>