<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:pre1="http://soprabanking.com/amplitude/savings/termDeposit"
xmlns:preAmp="http://soprabanking.com/amplitude"
targetNamespace="http://soprabanking.com/amplitude"
name="getTDGenAmendmentsDetail">

	<wsdl:types>
		<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
			<xsd:import namespace="http://soprabanking.com/amplitude/savings/termDeposit" schemaLocation="../FlowDescription/getTDGenAmendmentsDetail.xsd"/>
		</xsd:schema>
	</wsdl:types>

	<wsdl:message name="getTDGenAmendmentsDetailRequestFlow">
		<wsdl:part name="getTDGenAmendmentsDetailRequestFlow" element="pre1:getTDGenAmendmentsDetailRequestFlow"/>
	</wsdl:message>

	<wsdl:message name="getTDGenAmendmentsDetailResponseFlow">
		<wsdl:part name="getTDGenAmendmentsDetailResponseFlow" element="pre1:getTDGenAmendmentsDetailResponseFlow"/>
	</wsdl:message>

	<wsdl:portType name="getTDGenAmendmentsDetail">
		<wsdl:operation name="getTDGenAmendmentsDetail">
			<wsdl:input message="preAmp:getTDGenAmendmentsDetailRequestFlow" name="getTDGenAmendmentsDetailRequestFlow"/>
			<wsdl:output message="preAmp:getTDGenAmendmentsDetailResponseFlow" name="getTDGenAmendmentsDetailResponseFlow"/>
		</wsdl:operation>
	</wsdl:portType>

	<wsdl:binding name="getTDGenAmendmentsDetail-binding" type="preAmp:getTDGenAmendmentsDetail">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="getTDGenAmendmentsDetail">
			<soap:operation soapAction="getTDGenAmendmentsDetail"/>
			<wsdl:input name="getTDGenAmendmentsDetailRequestFlow">
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output name="getTDGenAmendmentsDetailResponseFlow">
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>

	<wsdl:service name="getTDGenAmendmentsDetail">
		<wsdl:port binding="preAmp:getTDGenAmendmentsDetail-binding" name="getTDGenAmendmentsDetail">
			<soap:address location="http://localhost:8080/getTDGenAmendmentsDetail"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>